/*
 * Navitas Enquiry-to-Offer Value-Chain
 * This is a sample Enquiry-to-Offer-Value-Chain server.  You can find out more about Navitas at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.navitas.ospoc.enq2offer01.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Application
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-23T15:45:59.374+10:00")
public class Application {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("prospectId")
  private String prospectId = null;

  @SerializedName("institutionId")
  private String institutionId = null;

  @SerializedName("courseId")
  private String courseId = null;

  /**
   * Application Status
   */
  public enum AppStatusEnum {
    @SerializedName("placed")
    PLACED("placed"),
    
    @SerializedName("approved")
    APPROVED("approved"),
    
    @SerializedName("complete")
    COMPLETE("complete");

    private String value;

    AppStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("appStatus")
  private AppStatusEnum appStatus = null;

  public Application id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Application prospectId(String prospectId) {
    this.prospectId = prospectId;
    return this;
  }

   /**
   * Get prospectId
   * @return prospectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProspectId() {
    return prospectId;
  }

  public void setProspectId(String prospectId) {
    this.prospectId = prospectId;
  }

  public Application institutionId(String institutionId) {
    this.institutionId = institutionId;
    return this;
  }

   /**
   * Get institutionId
   * @return institutionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstitutionId() {
    return institutionId;
  }

  public void setInstitutionId(String institutionId) {
    this.institutionId = institutionId;
  }

  public Application courseId(String courseId) {
    this.courseId = courseId;
    return this;
  }

   /**
   * Get courseId
   * @return courseId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCourseId() {
    return courseId;
  }

  public void setCourseId(String courseId) {
    this.courseId = courseId;
  }

  public Application appStatus(AppStatusEnum appStatus) {
    this.appStatus = appStatus;
    return this;
  }

   /**
   * Application Status
   * @return appStatus
  **/
  @ApiModelProperty(example = "null", value = "Application Status")
  public AppStatusEnum getAppStatus() {
    return appStatus;
  }

  public void setAppStatus(AppStatusEnum appStatus) {
    this.appStatus = appStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.id, application.id) &&
        Objects.equals(this.prospectId, application.prospectId) &&
        Objects.equals(this.institutionId, application.institutionId) &&
        Objects.equals(this.courseId, application.courseId) &&
        Objects.equals(this.appStatus, application.appStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, prospectId, institutionId, courseId, appStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    prospectId: ").append(toIndentedString(prospectId)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("    courseId: ").append(toIndentedString(courseId)).append("\n");
    sb.append("    appStatus: ").append(toIndentedString(appStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

